In [40]:
import requests
import pandas as pd
from pathlib import Path
from datetime import datetime as dt

In [14]:
url = 'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=GOOG&interval=5min&apikey=3B3IE0VNJFZBBMRY'
r = requests.get(url)
data = r.json()
data

{'Meta Data': {'1. Information': 'Intraday (5min) open, high, low, close prices and volume',
  '2. Symbol': 'GOOG',
  '3. Last Refreshed': '2022-10-07 20:00:00',
  '4. Interval': '5min',
  '5. Output Size': 'Compact',
  '6. Time Zone': 'US/Eastern'},
 'Time Series (5min)': {'2022-10-07 20:00:00': {'1. open': '99.3500',
   '2. high': '99.5600',
   '3. low': '99.3400',
   '4. close': '99.5600',
   '5. volume': '1777'},
  '2022-10-07 19:55:00': {'1. open': '99.4500',
   '2. high': '99.4500',
   '3. low': '99.4000',
   '4. close': '99.4000',
   '5. volume': '633'},
  '2022-10-07 19:50:00': {'1. open': '99.3500',
   '2. high': '99.4300',
   '3. low': '99.3500',
   '4. close': '99.4300',
   '5. volume': '994'},
  '2022-10-07 19:45:00': {'1. open': '99.4200',
   '2. high': '99.4200',
   '3. low': '99.4000',
   '4. close': '99.4000',
   '5. volume': '932'},
  '2022-10-07 19:40:00': {'1. open': '99.4200',
   '2. high': '99.4200',
   '3. low': '99.4200',
   '4. close': '99.4200',
   '5. volume': '884'},
  '2022-10-07 19:35:00': {'1. open': '99.5000',
   '2. high': '99.5000',
   '3. low': '99.4200',
   '4. close': '99.4200',
   '5. volume': '1196'},
  '2022-10-07 19:30:00': {'1. open': '99.5200',
   '2. high': '99.5200',
   '3. low': '99.5200',
   '4. close': '99.5200',
   '5. volume': '456'},
  '2022-10-07 19:25:00': {'1. open': '99.5200',
   '2. high': '99.5200',
   '3. low': '99.5200',
   '4. close': '99.5200',
   '5. volume': '130'},
  '2022-10-07 19:10:00': {'1. open': '99.5100',
   '2. high': '99.5100',
   '3. low': '99.5100',
   '4. close': '99.5100',
   '5. volume': '651'},
  '2022-10-07 19:00:00': {'1. open': '99.5600',
   '2. high': '99.5600',
   '3. low': '99.5600',
   '4. close': '99.5600',
   '5. volume': '210'},
  '2022-10-07 18:55:00': {'1. open': '99.5900',
   '2. high': '99.5900',
   '3. low': '99.5900',
   '4. close': '99.5900',
   '5. volume': '150'},
  '2022-10-07 18:50:00': {'1. open': '99.5900',
   '2. high': '99.5900',
   '3. low': '99.5900',
   '4. close': '99.5900',
   '5. volume': '132'},
  '2022-10-07 18:35:00': {'1. open': '99.5600',
   '2. high': '99.5600',
   '3. low': '99.5600',
   '4. close': '99.5600',
   '5. volume': '238'},
  '2022-10-07 18:30:00': {'1. open': '99.5300',
   '2. high': '99.5400',
   '3. low': '99.5300',
   '4. close': '99.5400',
   '5. volume': '1208'},
  '2022-10-07 18:25:00': {'1. open': '99.5500',
   '2. high': '99.5500',
   '3. low': '99.5500',
   '4. close': '99.5500',
   '5. volume': '4585'},
  '2022-10-07 18:20:00': {'1. open': '99.5600',
   '2. high': '99.5601',
   '3. low': '99.5500',
   '4. close': '99.5500',
   '5. volume': '999'},
  '2022-10-07 18:15:00': {'1. open': '99.5600',
   '2. high': '99.5600',
   '3. low': '99.5600',
   '4. close': '99.5600',
   '5. volume': '152'},
  '2022-10-07 18:10:00': {'1. open': '99.5600',
   '2. high': '99.5600',
   '3. low': '99.5600',
   '4. close': '99.5600',
   '5. volume': '258'},
  '2022-10-07 18:05:00': {'1. open': '99.6100',
   '2. high': '99.6100',
   '3. low': '99.5600',
   '4. close': '99.5600',
   '5. volume': '3132'},
  '2022-10-07 18:00:00': {'1. open': '99.6100',
   '2. high': '99.6100',
   '3. low': '99.6100',
   '4. close': '99.6100',
   '5. volume': '102'},
  '2022-10-07 17:55:00': {'1. open': '99.6300',
   '2. high': '99.6300',
   '3. low': '99.6300',
   '4. close': '99.6300',
   '5. volume': '106'},
  '2022-10-07 17:50:00': {'1. open': '99.6400',
   '2. high': '99.6400',
   '3. low': '99.6400',
   '4. close': '99.6400',
   '5. volume': '151'},
  '2022-10-07 17:45:00': {'1. open': '99.6300',
   '2. high': '99.6300',
   '3. low': '99.6300',
   '4. close': '99.6300',
   '5. volume': '400'},
  '2022-10-07 17:40:00': {'1. open': '99.6300',
   '2. high': '99.6300',
   '3. low': '99.6300',
   '4. close': '99.6300',
   '5. volume': '100'},
  '2022-10-07 17:35:00': {'1. open': '99.6200',
   '2. high': '99.6200',
   '3. low': '99.6200',
   '4. close': '99.6200',
   '5. volume': '105'},
  '2022-10-07 17:15:00': {'1. open': '99.6700',
   '2. high': '99.6700',
   '3. low': '99.5600',
   '4. close': '99.5600',
   '5. volume': '752'},
  '2022-10-07 17:00:00': {'1. open': '99.6000',
   '2. high': '99.6800',
   '3. low': '99.6000',
   '4. close': '99.6800',
   '5. volume': '2187'},
  '2022-10-07 16:55:00': {'1. open': '99.6500',
   '2. high': '99.6500',
   '3. low': '99.6200',
   '4. close': '99.6200',
   '5. volume': '1774'},
  '2022-10-07 16:50:00': {'1. open': '99.6400',
   '2. high': '99.6400',
   '3. low': '99.6400',
   '4. close': '99.6400',
   '5. volume': '535'},
  '2022-10-07 16:40:00': {'1. open': '99.6100',
   '2. high': '99.6399',
   '3. low': '99.5600',
   '4. close': '99.5600',
   '5. volume': '7344'},
  '2022-10-07 16:35:00': {'1. open': '99.5900',
   '2. high': '99.6000',
   '3. low': '99.5900',
   '4. close': '99.6000',
   '5. volume': '314'},
  '2022-10-07 16:30:00': {'1. open': '99.6200',
   '2. high': '99.6200',
   '3. low': '99.5500',
   '4. close': '99.5500',
   '5. volume': '10103'},
  '2022-10-07 16:25:00': {'1. open': '99.5900',
   '2. high': '99.6300',
   '3. low': '99.5800',
   '4. close': '99.6201',
   '5. volume': '999'},
  '2022-10-07 16:20:00': {'1. open': '99.6500',
   '2. high': '99.6500',
   '3. low': '99.6200',
   '4. close': '99.6200',
   '5. volume': '509'},
  '2022-10-07 16:15:00': {'1. open': '99.5700',
   '2. high': '99.7200',
   '3. low': '99.5600',
   '4. close': '99.7200',
   '5. volume': '23499'},
  '2022-10-07 16:10:00': {'1. open': '99.6900',
   '2. high': '99.7000',
   '3. low': '99.5700',
   '4. close': '99.6000',
   '5. volume': '48460'},
  '2022-10-07 16:05:00': {'1. open': '99.5700',
   '2. high': '99.8900',
   '3. low': '99.5700',
   '4. close': '99.6900',
   '5. volume': '839648'},
  '2022-10-07 16:00:00': {'1. open': '99.5300',
   '2. high': '99.7600',
   '3. low': '99.4200',
   '4. close': '99.6500',
   '5. volume': '1817533'},
  '2022-10-07 15:55:00': {'1. open': '99.4400',
   '2. high': '99.7800',
   '3. low': '99.3600',
   '4. close': '99.5300',
   '5. volume': '840233'},
  '2022-10-07 15:50:00': {'1. open': '99.5600',
   '2. high': '99.5700',
   '3. low': '99.3650',
   '4. close': '99.4300',
   '5. volume': '377385'},
  '2022-10-07 15:45:00': {'1. open': '99.5801',
   '2. high': '99.7200',
   '3. low': '99.4900',
   '4. close': '99.5600',
   '5. volume': '454946'},
  '2022-10-07 15:40:00': {'1. open': '99.2800',
   '2. high': '99.5900',
   '3. low': '99.2550',
   '4. close': '99.5900',
   '5. volume': '320402'},
  '2022-10-07 15:35:00': {'1. open': '99.4900',
   '2. high': '99.5000',
   '3. low': '99.2100',
   '4. close': '99.2700',
   '5. volume': '293568'},
  '2022-10-07 15:30:00': {'1. open': '99.6150',
   '2. high': '99.6300',
   '3. low': '99.3600',
   '4. close': '99.5000',
   '5. volume': '263224'},
  '2022-10-07 15:25:00': {'1. open': '99.6500',
   '2. high': '99.7031',
   '3. low': '99.5450',
   '4. close': '99.6100',
   '5. volume': '261555'},
  '2022-10-07 15:20:00': {'1. open': '99.7500',
   '2. high': '99.8200',
   '3. low': '99.6100',
   '4. close': '99.6600',
   '5. volume': '195727'},
  '2022-10-07 15:15:00': {'1. open': '99.8900',
   '2. high': '99.9700',
   '3. low': '99.7200',
   '4. close': '99.7499',
   '5. volume': '223635'},
  '2022-10-07 15:10:00': {'1. open': '100.0900',
   '2. high': '100.0950',
   '3. low': '99.8050',
   '4. close': '99.8850',
   '5. volume': '175739'},
  '2022-10-07 15:05:00': {'1. open': '99.8300',
   '2. high': '100.1000',
   '3. low': '99.8300',
   '4. close': '100.1000',
   '5. volume': '171781'},
  '2022-10-07 15:00:00': {'1. open': '99.7800',
   '2. high': '99.8600',
   '3. low': '99.7200',
   '4. close': '99.8300',
   '5. volume': '168309'},
  '2022-10-07 14:55:00': {'1. open': '99.7050',
   '2. high': '99.7850',
   '3. low': '99.6600',
   '4. close': '99.7799',
   '5. volume': '179802'},
  '2022-10-07 14:50:00': {'1. open': '99.5700',
   '2. high': '99.7000',
   '3. low': '99.5400',
   '4. close': '99.6950',
   '5. volume': '183714'},
  '2022-10-07 14:45:00': {'1. open': '99.5300',
   '2. high': '99.6690',
   '3. low': '99.5300',
   '4. close': '99.5700',
   '5. volume': '131054'},
  '2022-10-07 14:40:00': {'1. open': '99.4200',
   '2. high': '99.6400',
   '3. low': '99.4200',
   '4. close': '99.5378',
   '5. volume': '158976'},
  '2022-10-07 14:35:00': {'1. open': '99.3900',
   '2. high': '99.4350',
   '3. low': '99.2700',
   '4. close': '99.4200',
   '5. volume': '193769'},
  '2022-10-07 14:30:00': {'1. open': '99.4000',
   '2. high': '99.4900',
   '3. low': '99.3500',
   '4. close': '99.3900',
   '5. volume': '173167'},
  '2022-10-07 14:25:00': {'1. open': '99.5300',
   '2. high': '99.5700',
   '3. low': '99.3500',
   '4. close': '99.3900',
   '5. volume': '181553'},
  '2022-10-07 14:20:00': {'1. open': '99.6800',
   '2. high': '99.7300',
   '3. low': '99.5100',
   '4. close': '99.5350',
   '5. volume': '133298'},
  '2022-10-07 14:15:00': {'1. open': '99.5700',
   '2. high': '99.7001',
   '3. low': '99.4200',
   '4. close': '99.6800',
   '5. volume': '170238'},
  '2022-10-07 14:10:00': {'1. open': '99.5100',
   '2. high': '99.6200',
   '3. low': '99.5000',
   '4. close': '99.5800',
   '5. volume': '122766'},
  '2022-10-07 14:05:00': {'1. open': '99.4900',
   '2. high': '99.5800',
   '3. low': '99.4300',
   '4. close': '99.5150',
   '5. volume': '182280'},
  '2022-10-07 14:00:00': {'1. open': '99.5700',
   '2. high': '99.6600',
   '3. low': '99.4300',
   '4. close': '99.4900',
   '5. volume': '158925'},
  '2022-10-07 13:55:00': {'1. open': '99.6600',
   '2. high': '99.7194',
   '3. low': '99.5650',
   '4. close': '99.5799',
   '5. volume': '129149'},
  '2022-10-07 13:50:00': {'1. open': '99.7700',
   '2. high': '99.8900',
   '3. low': '99.6550',
   '4. close': '99.6650',
   '5. volume': '174263'},
  '2022-10-07 13:45:00': {'1. open': '99.7100',
   '2. high': '99.8900',
   '3. low': '99.7000',
   '4. close': '99.7800',
   '5. volume': '148333'},
  '2022-10-07 13:40:00': {'1. open': '99.7200',
   '2. high': '99.7800',
   '3. low': '99.6550',
   '4. close': '99.7150',
   '5. volume': '122376'},
  '2022-10-07 13:35:00': {'1. open': '99.8500',
   '2. high': '99.8500',
   '3. low': '99.6750',
   '4. close': '99.7283',
   '5. volume': '148724'},
  '2022-10-07 13:30:00': {'1. open': '99.7800',
   '2. high': '99.9650',
   '3. low': '99.7700',
   '4. close': '99.8500',
   '5. volume': '128095'},
  '2022-10-07 13:25:00': {'1. open': '99.9700',
   '2. high': '99.9850',
   '3. low': '99.7800',
   '4. close': '99.7800',
   '5. volume': '121085'},
  '2022-10-07 13:20:00': {'1. open': '99.9100',
   '2. high': '100.0300',
   '3. low': '99.8600',
   '4. close': '99.9800',
   '5. volume': '140688'},
  '2022-10-07 13:15:00': {'1. open': '99.6800',
   '2. high': '99.9100',
   '3. low': '99.6800',
   '4. close': '99.9098',
   '5. volume': '149416'},
  '2022-10-07 13:10:00': {'1. open': '99.7700',
   '2. high': '99.8358',
   '3. low': '99.6200',
   '4. close': '99.6737',
   '5. volume': '128559'},
  '2022-10-07 13:05:00': {'1. open': '99.8900',
   '2. high': '99.8900',
   '3. low': '99.6900',
   '4. close': '99.7615',
   '5. volume': '157706'},
  '2022-10-07 13:00:00': {'1. open': '99.8094',
   '2. high': '99.9100',
   '3. low': '99.7975',
   '4. close': '99.9000',
   '5. volume': '129056'},
  '2022-10-07 12:55:00': {'1. open': '99.7800',
   '2. high': '99.8550',
   '3. low': '99.7400',
   '4. close': '99.8000',
   '5. volume': '122139'},
  '2022-10-07 12:50:00': {'1. open': '99.9600',
   '2. high': '99.9800',
   '3. low': '99.7498',
   '4. close': '99.7700',
   '5. volume': '148642'},
  '2022-10-07 12:45:00': {'1. open': '100.0500',
   '2. high': '100.0700',
   '3. low': '99.9100',
   '4. close': '99.9500',
   '5. volume': '127086'},
  '2022-10-07 12:40:00': {'1. open': '99.9100',
   '2. high': '100.0500',
   '3. low': '99.9000',
   '4. close': '100.0488',
   '5. volume': '122494'},
  '2022-10-07 12:35:00': {'1. open': '99.9300',
   '2. high': '99.9900',
   '3. low': '99.8500',
   '4. close': '99.9100',
   '5. volume': '172077'},
  '2022-10-07 12:30:00': {'1. open': '99.9100',
   '2. high': '100.0600',
   '3. low': '99.8500',
   '4. close': '99.9400',
   '5. volume': '168160'},
  '2022-10-07 12:25:00': {'1. open': '100.2200',
   '2. high': '100.2600',
   '3. low': '99.9100',
   '4. close': '99.9100',
   '5. volume': '248627'},
  '2022-10-07 12:20:00': {'1. open': '100.2100',
   '2. high': '100.3200',
   '3. low': '100.1400',
   '4. close': '100.2150',
   '5. volume': '136867'},
  '2022-10-07 12:15:00': {'1. open': '100.3100',
   '2. high': '100.3650',
   '3. low': '100.1950',
   '4. close': '100.2000',
   '5. volume': '125596'},
  '2022-10-07 12:10:00': {'1. open': '100.3200',
   '2. high': '100.3600',
   '3. low': '100.1800',
   '4. close': '100.3100',
   '5. volume': '118518'},
  '2022-10-07 12:05:00': {'1. open': '100.2500',
   '2. high': '100.3100',
   '3. low': '100.1700',
   '4. close': '100.3100',
   '5. volume': '139159'},
  '2022-10-07 12:00:00': {'1. open': '100.1500',
   '2. high': '100.3500',
   '3. low': '100.1250',
   '4. close': '100.2500',
   '5. volume': '123106'},
  '2022-10-07 11:55:00': {'1. open': '100.1100',
   '2. high': '100.2800',
   '3. low': '100.0600',
   '4. close': '100.1525',
   '5. volume': '125005'},
  '2022-10-07 11:50:00': {'1. open': '100.2100',
   '2. high': '100.2550',
   '3. low': '100.0900',
   '4. close': '100.1010',
   '5. volume': '155306'},
  '2022-10-07 11:45:00': {'1. open': '100.3200',
   '2. high': '100.3800',
   '3. low': '100.0650',
   '4. close': '100.2000',
   '5. volume': '174051'},
  '2022-10-07 11:40:00': {'1. open': '100.2250',
   '2. high': '100.4500',
   '3. low': '100.2250',
   '4. close': '100.3290',
   '5. volume': '143688'},
  '2022-10-07 11:35:00': {'1. open': '100.3900',
   '2. high': '100.4900',
   '3. low': '100.1950',
   '4. close': '100.2200',
   '5. volume': '145373'},
  '2022-10-07 11:30:00': {'1. open': '100.2384',
   '2. high': '100.4100',
   '3. low': '100.1600',
   '4. close': '100.3900',
   '5. volume': '176082'},
  '2022-10-07 11:25:00': {'1. open': '100.3200',
   '2. high': '100.3600',
   '3. low': '100.1600',
   '4. close': '100.2300',
   '5. volume': '220553'},
  '2022-10-07 11:20:00': {'1. open': '100.6350',
   '2. high': '100.7300',
   '3. low': '100.3100',
   '4. close': '100.3200',
   '5. volume': '192981'},
  '2022-10-07 11:15:00': {'1. open': '100.6100',
   '2. high': '100.7390',
   '3. low': '100.4900',
   '4. close': '100.6300',
   '5. volume': '171871'},
  '2022-10-07 11:10:00': {'1. open': '101.0900',
   '2. high': '101.0900',
   '3. low': '100.6100',
   '4. close': '100.6100',
   '5. volume': '185531'},
  '2022-10-07 11:05:00': {'1. open': '100.7600',
   '2. high': '101.0900',
   '3. low': '100.7600',
   '4. close': '101.0900',
   '5. volume': '342552'},
  '2022-10-07 11:00:00': {'1. open': '100.7800',
   '2. high': '100.9550',
   '3. low': '100.7250',
   '4. close': '100.7700',
   '5. volume': '386668'},
  '2022-10-07 10:55:00': {'1. open': '100.7300',
   '2. high': '100.8500',
   '3. low': '100.5500',
   '4. close': '100.7750',
   '5. volume': '480951'},
  '2022-10-07 10:50:00': {'1. open': '100.5500',
   '2. high': '100.8400',
   '3. low': '100.5000',
   '4. close': '100.7300',
   '5. volume': '273143'}}}

In [3]:
data.keys()

dict_keys(['Meta Data', 'Time Series (5min)'])

In [4]:
data.get('Time Series (5min)')

{'2022-10-07 20:00:00': {'1. open': '99.3500',
  '2. high': '99.5600',
  '3. low': '99.3400',
  '4. close': '99.5600',
  '5. volume': '1777'},
 '2022-10-07 19:55:00': {'1. open': '99.4500',
  '2. high': '99.4500',
  '3. low': '99.4000',
  '4. close': '99.4000',
  '5. volume': '633'},
 '2022-10-07 19:50:00': {'1. open': '99.3500',
  '2. high': '99.4300',
  '3. low': '99.3500',
  '4. close': '99.4300',
  '5. volume': '994'},
 '2022-10-07 19:45:00': {'1. open': '99.4200',
  '2. high': '99.4200',
  '3. low': '99.4000',
  '4. close': '99.4000',
  '5. volume': '932'},
 '2022-10-07 19:40:00': {'1. open': '99.4200',
  '2. high': '99.4200',
  '3. low': '99.4200',
  '4. close': '99.4200',
  '5. volume': '884'},
 '2022-10-07 19:35:00': {'1. open': '99.5000',
  '2. high': '99.5000',
  '3. low': '99.4200',
  '4. close': '99.4200',
  '5. volume': '1196'},
 '2022-10-07 19:30:00': {'1. open': '99.5200',
  '2. high': '99.5200',
  '3. low': '99.5200',
  '4. close': '99.5200',
  '5. volume': '456'},
 '2022-10-07 19:25:00': {'1. open': '99.5200',
  '2. high': '99.5200',
  '3. low': '99.5200',
  '4. close': '99.5200',
  '5. volume': '130'},
 '2022-10-07 19:10:00': {'1. open': '99.5100',
  '2. high': '99.5100',
  '3. low': '99.5100',
  '4. close': '99.5100',
  '5. volume': '651'},
 '2022-10-07 19:00:00': {'1. open': '99.5600',
  '2. high': '99.5600',
  '3. low': '99.5600',
  '4. close': '99.5600',
  '5. volume': '210'},
 '2022-10-07 18:55:00': {'1. open': '99.5900',
  '2. high': '99.5900',
  '3. low': '99.5900',
  '4. close': '99.5900',
  '5. volume': '150'},
 '2022-10-07 18:50:00': {'1. open': '99.5900',
  '2. high': '99.5900',
  '3. low': '99.5900',
  '4. close': '99.5900',
  '5. volume': '132'},
 '2022-10-07 18:35:00': {'1. open': '99.5600',
  '2. high': '99.5600',
  '3. low': '99.5600',
  '4. close': '99.5600',
  '5. volume': '238'},
 '2022-10-07 18:30:00': {'1. open': '99.5300',
  '2. high': '99.5400',
  '3. low': '99.5300',
  '4. close': '99.5400',
  '5. volume': '1208'},
 '2022-10-07 18:25:00': {'1. open': '99.5500',
  '2. high': '99.5500',
  '3. low': '99.5500',
  '4. close': '99.5500',
  '5. volume': '4585'},
 '2022-10-07 18:20:00': {'1. open': '99.5600',
  '2. high': '99.5601',
  '3. low': '99.5500',
  '4. close': '99.5500',
  '5. volume': '999'},
 '2022-10-07 18:15:00': {'1. open': '99.5600',
  '2. high': '99.5600',
  '3. low': '99.5600',
  '4. close': '99.5600',
  '5. volume': '152'},
 '2022-10-07 18:10:00': {'1. open': '99.5600',
  '2. high': '99.5600',
  '3. low': '99.5600',
  '4. close': '99.5600',
  '5. volume': '258'},
 '2022-10-07 18:05:00': {'1. open': '99.6100',
  '2. high': '99.6100',
  '3. low': '99.5600',
  '4. close': '99.5600',
  '5. volume': '3132'},
 '2022-10-07 18:00:00': {'1. open': '99.6100',
  '2. high': '99.6100',
  '3. low': '99.6100',
  '4. close': '99.6100',
  '5. volume': '102'},
 '2022-10-07 17:55:00': {'1. open': '99.6300',
  '2. high': '99.6300',
  '3. low': '99.6300',
  '4. close': '99.6300',
  '5. volume': '106'},
 '2022-10-07 17:50:00': {'1. open': '99.6400',
  '2. high': '99.6400',
  '3. low': '99.6400',
  '4. close': '99.6400',
  '5. volume': '151'},
 '2022-10-07 17:45:00': {'1. open': '99.6300',
  '2. high': '99.6300',
  '3. low': '99.6300',
  '4. close': '99.6300',
  '5. volume': '400'},
 '2022-10-07 17:40:00': {'1. open': '99.6300',
  '2. high': '99.6300',
  '3. low': '99.6300',
  '4. close': '99.6300',
  '5. volume': '100'},
 '2022-10-07 17:35:00': {'1. open': '99.6200',
  '2. high': '99.6200',
  '3. low': '99.6200',
  '4. close': '99.6200',
  '5. volume': '105'},
 '2022-10-07 17:15:00': {'1. open': '99.6700',
  '2. high': '99.6700',
  '3. low': '99.5600',
  '4. close': '99.5600',
  '5. volume': '752'},
 '2022-10-07 17:00:00': {'1. open': '99.6000',
  '2. high': '99.6800',
  '3. low': '99.6000',
  '4. close': '99.6800',
  '5. volume': '2187'},
 '2022-10-07 16:55:00': {'1. open': '99.6500',
  '2. high': '99.6500',
  '3. low': '99.6200',
  '4. close': '99.6200',
  '5. volume': '1774'},
 '2022-10-07 16:50:00': {'1. open': '99.6400',
  '2. high': '99.6400',
  '3. low': '99.6400',
  '4. close': '99.6400',
  '5. volume': '535'},
 '2022-10-07 16:40:00': {'1. open': '99.6100',
  '2. high': '99.6399',
  '3. low': '99.5600',
  '4. close': '99.5600',
  '5. volume': '7344'},
 '2022-10-07 16:35:00': {'1. open': '99.5900',
  '2. high': '99.6000',
  '3. low': '99.5900',
  '4. close': '99.6000',
  '5. volume': '314'},
 '2022-10-07 16:30:00': {'1. open': '99.6200',
  '2. high': '99.6200',
  '3. low': '99.5500',
  '4. close': '99.5500',
  '5. volume': '10103'},
 '2022-10-07 16:25:00': {'1. open': '99.5900',
  '2. high': '99.6300',
  '3. low': '99.5800',
  '4. close': '99.6201',
  '5. volume': '999'},
 '2022-10-07 16:20:00': {'1. open': '99.6500',
  '2. high': '99.6500',
  '3. low': '99.6200',
  '4. close': '99.6200',
  '5. volume': '509'},
 '2022-10-07 16:15:00': {'1. open': '99.5700',
  '2. high': '99.7200',
  '3. low': '99.5600',
  '4. close': '99.7200',
  '5. volume': '23499'},
 '2022-10-07 16:10:00': {'1. open': '99.6900',
  '2. high': '99.7000',
  '3. low': '99.5700',
  '4. close': '99.6000',
  '5. volume': '48460'},
 '2022-10-07 16:05:00': {'1. open': '99.5700',
  '2. high': '99.8900',
  '3. low': '99.5700',
  '4. close': '99.6900',
  '5. volume': '839648'},
 '2022-10-07 16:00:00': {'1. open': '99.5300',
  '2. high': '99.7600',
  '3. low': '99.4200',
  '4. close': '99.6500',
  '5. volume': '1817533'},
 '2022-10-07 15:55:00': {'1. open': '99.4400',
  '2. high': '99.7800',
  '3. low': '99.3600',
  '4. close': '99.5300',
  '5. volume': '840233'},
 '2022-10-07 15:50:00': {'1. open': '99.5600',
  '2. high': '99.5700',
  '3. low': '99.3650',
  '4. close': '99.4300',
  '5. volume': '377385'},
 '2022-10-07 15:45:00': {'1. open': '99.5801',
  '2. high': '99.7200',
  '3. low': '99.4900',
  '4. close': '99.5600',
  '5. volume': '454946'},
 '2022-10-07 15:40:00': {'1. open': '99.2800',
  '2. high': '99.5900',
  '3. low': '99.2550',
  '4. close': '99.5900',
  '5. volume': '320402'},
 '2022-10-07 15:35:00': {'1. open': '99.4900',
  '2. high': '99.5000',
  '3. low': '99.2100',
  '4. close': '99.2700',
  '5. volume': '293568'},
 '2022-10-07 15:30:00': {'1. open': '99.6150',
  '2. high': '99.6300',
  '3. low': '99.3600',
  '4. close': '99.5000',
  '5. volume': '263224'},
 '2022-10-07 15:25:00': {'1. open': '99.6500',
  '2. high': '99.7031',
  '3. low': '99.5450',
  '4. close': '99.6100',
  '5. volume': '261555'},
 '2022-10-07 15:20:00': {'1. open': '99.7500',
  '2. high': '99.8200',
  '3. low': '99.6100',
  '4. close': '99.6600',
  '5. volume': '195727'},
 '2022-10-07 15:15:00': {'1. open': '99.8900',
  '2. high': '99.9700',
  '3. low': '99.7200',
  '4. close': '99.7499',
  '5. volume': '223635'},
 '2022-10-07 15:10:00': {'1. open': '100.0900',
  '2. high': '100.0950',
  '3. low': '99.8050',
  '4. close': '99.8850',
  '5. volume': '175739'},
 '2022-10-07 15:05:00': {'1. open': '99.8300',
  '2. high': '100.1000',
  '3. low': '99.8300',
  '4. close': '100.1000',
  '5. volume': '171781'},
 '2022-10-07 15:00:00': {'1. open': '99.7800',
  '2. high': '99.8600',
  '3. low': '99.7200',
  '4. close': '99.8300',
  '5. volume': '168309'},
 '2022-10-07 14:55:00': {'1. open': '99.7050',
  '2. high': '99.7850',
  '3. low': '99.6600',
  '4. close': '99.7799',
  '5. volume': '179802'},
 '2022-10-07 14:50:00': {'1. open': '99.5700',
  '2. high': '99.7000',
  '3. low': '99.5400',
  '4. close': '99.6950',
  '5. volume': '183714'},
 '2022-10-07 14:45:00': {'1. open': '99.5300',
  '2. high': '99.6690',
  '3. low': '99.5300',
  '4. close': '99.5700',
  '5. volume': '131054'},
 '2022-10-07 14:40:00': {'1. open': '99.4200',
  '2. high': '99.6400',
  '3. low': '99.4200',
  '4. close': '99.5378',
  '5. volume': '158976'},
 '2022-10-07 14:35:00': {'1. open': '99.3900',
  '2. high': '99.4350',
  '3. low': '99.2700',
  '4. close': '99.4200',
  '5. volume': '193769'},
 '2022-10-07 14:30:00': {'1. open': '99.4000',
  '2. high': '99.4900',
  '3. low': '99.3500',
  '4. close': '99.3900',
  '5. volume': '173167'},
 '2022-10-07 14:25:00': {'1. open': '99.5300',
  '2. high': '99.5700',
  '3. low': '99.3500',
  '4. close': '99.3900',
  '5. volume': '181553'},
 '2022-10-07 14:20:00': {'1. open': '99.6800',
  '2. high': '99.7300',
  '3. low': '99.5100',
  '4. close': '99.5350',
  '5. volume': '133298'},
 '2022-10-07 14:15:00': {'1. open': '99.5700',
  '2. high': '99.7001',
  '3. low': '99.4200',
  '4. close': '99.6800',
  '5. volume': '170238'},
 '2022-10-07 14:10:00': {'1. open': '99.5100',
  '2. high': '99.6200',
  '3. low': '99.5000',
  '4. close': '99.5800',
  '5. volume': '122766'},
 '2022-10-07 14:05:00': {'1. open': '99.4900',
  '2. high': '99.5800',
  '3. low': '99.4300',
  '4. close': '99.5150',
  '5. volume': '182280'},
 '2022-10-07 14:00:00': {'1. open': '99.5700',
  '2. high': '99.6600',
  '3. low': '99.4300',
  '4. close': '99.4900',
  '5. volume': '158925'},
 '2022-10-07 13:55:00': {'1. open': '99.6600',
  '2. high': '99.7194',
  '3. low': '99.5650',
  '4. close': '99.5799',
  '5. volume': '129149'},
 '2022-10-07 13:50:00': {'1. open': '99.7700',
  '2. high': '99.8900',
  '3. low': '99.6550',
  '4. close': '99.6650',
  '5. volume': '174263'},
 '2022-10-07 13:45:00': {'1. open': '99.7100',
  '2. high': '99.8900',
  '3. low': '99.7000',
  '4. close': '99.7800',
  '5. volume': '148333'},
 '2022-10-07 13:40:00': {'1. open': '99.7200',
  '2. high': '99.7800',
  '3. low': '99.6550',
  '4. close': '99.7150',
  '5. volume': '122376'},
 '2022-10-07 13:35:00': {'1. open': '99.8500',
  '2. high': '99.8500',
  '3. low': '99.6750',
  '4. close': '99.7283',
  '5. volume': '148724'},
 '2022-10-07 13:30:00': {'1. open': '99.7800',
  '2. high': '99.9650',
  '3. low': '99.7700',
  '4. close': '99.8500',
  '5. volume': '128095'},
 '2022-10-07 13:25:00': {'1. open': '99.9700',
  '2. high': '99.9850',
  '3. low': '99.7800',
  '4. close': '99.7800',
  '5. volume': '121085'},
 '2022-10-07 13:20:00': {'1. open': '99.9100',
  '2. high': '100.0300',
  '3. low': '99.8600',
  '4. close': '99.9800',
  '5. volume': '140688'},
 '2022-10-07 13:15:00': {'1. open': '99.6800',
  '2. high': '99.9100',
  '3. low': '99.6800',
  '4. close': '99.9098',
  '5. volume': '149416'},
 '2022-10-07 13:10:00': {'1. open': '99.7700',
  '2. high': '99.8358',
  '3. low': '99.6200',
  '4. close': '99.6737',
  '5. volume': '128559'},
 '2022-10-07 13:05:00': {'1. open': '99.8900',
  '2. high': '99.8900',
  '3. low': '99.6900',
  '4. close': '99.7615',
  '5. volume': '157706'},
 '2022-10-07 13:00:00': {'1. open': '99.8094',
  '2. high': '99.9100',
  '3. low': '99.7975',
  '4. close': '99.9000',
  '5. volume': '129056'},
 '2022-10-07 12:55:00': {'1. open': '99.7800',
  '2. high': '99.8550',
  '3. low': '99.7400',
  '4. close': '99.8000',
  '5. volume': '122139'},
 '2022-10-07 12:50:00': {'1. open': '99.9600',
  '2. high': '99.9800',
  '3. low': '99.7498',
  '4. close': '99.7700',
  '5. volume': '148642'},
 '2022-10-07 12:45:00': {'1. open': '100.0500',
  '2. high': '100.0700',
  '3. low': '99.9100',
  '4. close': '99.9500',
  '5. volume': '127086'},
 '2022-10-07 12:40:00': {'1. open': '99.9100',
  '2. high': '100.0500',
  '3. low': '99.9000',
  '4. close': '100.0488',
  '5. volume': '122494'},
 '2022-10-07 12:35:00': {'1. open': '99.9300',
  '2. high': '99.9900',
  '3. low': '99.8500',
  '4. close': '99.9100',
  '5. volume': '172077'},
 '2022-10-07 12:30:00': {'1. open': '99.9100',
  '2. high': '100.0600',
  '3. low': '99.8500',
  '4. close': '99.9400',
  '5. volume': '168160'},
 '2022-10-07 12:25:00': {'1. open': '100.2200',
  '2. high': '100.2600',
  '3. low': '99.9100',
  '4. close': '99.9100',
  '5. volume': '248627'},
 '2022-10-07 12:20:00': {'1. open': '100.2100',
  '2. high': '100.3200',
  '3. low': '100.1400',
  '4. close': '100.2150',
  '5. volume': '136867'},
 '2022-10-07 12:15:00': {'1. open': '100.3100',
  '2. high': '100.3650',
  '3. low': '100.1950',
  '4. close': '100.2000',
  '5. volume': '125596'},
 '2022-10-07 12:10:00': {'1. open': '100.3200',
  '2. high': '100.3600',
  '3. low': '100.1800',
  '4. close': '100.3100',
  '5. volume': '118518'},
 '2022-10-07 12:05:00': {'1. open': '100.2500',
  '2. high': '100.3100',
  '3. low': '100.1700',
  '4. close': '100.3100',
  '5. volume': '139159'},
 '2022-10-07 12:00:00': {'1. open': '100.1500',
  '2. high': '100.3500',
  '3. low': '100.1250',
  '4. close': '100.2500',
  '5. volume': '123106'},
 '2022-10-07 11:55:00': {'1. open': '100.1100',
  '2. high': '100.2800',
  '3. low': '100.0600',
  '4. close': '100.1525',
  '5. volume': '125005'},
 '2022-10-07 11:50:00': {'1. open': '100.2100',
  '2. high': '100.2550',
  '3. low': '100.0900',
  '4. close': '100.1010',
  '5. volume': '155306'},
 '2022-10-07 11:45:00': {'1. open': '100.3200',
  '2. high': '100.3800',
  '3. low': '100.0650',
  '4. close': '100.2000',
  '5. volume': '174051'},
 '2022-10-07 11:40:00': {'1. open': '100.2250',
  '2. high': '100.4500',
  '3. low': '100.2250',
  '4. close': '100.3290',
  '5. volume': '143688'},
 '2022-10-07 11:35:00': {'1. open': '100.3900',
  '2. high': '100.4900',
  '3. low': '100.1950',
  '4. close': '100.2200',
  '5. volume': '145373'},
 '2022-10-07 11:30:00': {'1. open': '100.2384',
  '2. high': '100.4100',
  '3. low': '100.1600',
  '4. close': '100.3900',
  '5. volume': '176082'},
 '2022-10-07 11:25:00': {'1. open': '100.3200',
  '2. high': '100.3600',
  '3. low': '100.1600',
  '4. close': '100.2300',
  '5. volume': '220553'},
 '2022-10-07 11:20:00': {'1. open': '100.6350',
  '2. high': '100.7300',
  '3. low': '100.3100',
  '4. close': '100.3200',
  '5. volume': '192981'},
 '2022-10-07 11:15:00': {'1. open': '100.6100',
  '2. high': '100.7390',
  '3. low': '100.4900',
  '4. close': '100.6300',
  '5. volume': '171871'},
 '2022-10-07 11:10:00': {'1. open': '101.0900',
  '2. high': '101.0900',
  '3. low': '100.6100',
  '4. close': '100.6100',
  '5. volume': '185531'},
 '2022-10-07 11:05:00': {'1. open': '100.7600',
  '2. high': '101.0900',
  '3. low': '100.7600',
  '4. close': '101.0900',
  '5. volume': '342552'},
 '2022-10-07 11:00:00': {'1. open': '100.7800',
  '2. high': '100.9550',
  '3. low': '100.7250',
  '4. close': '100.7700',
  '5. volume': '386668'},
 '2022-10-07 10:55:00': {'1. open': '100.7300',
  '2. high': '100.8500',
  '3. low': '100.5500',
  '4. close': '100.7750',
  '5. volume': '480951'},
 '2022-10-07 10:50:00': {'1. open': '100.5500',
  '2. high': '100.8400',
  '3. low': '100.5000',
  '4. close': '100.7300',
  '5. volume': '273143'}}

In [18]:
df = pd.DataFrame(data.get('Time Series (5min)')).T.reset_index().rename(columns={'index':'datetime', 
                                                                             '1. open': 'open', 
                                                                             '2. high': 'high', 
                                                                             '3. low':'low', 
                                                                             '4. close': 'close', 
                                                                             '5. volume': 'volume'})

df

               datetime      open      high       low     close  volume
0   2022-10-07 20:00:00   99.3500   99.5600   99.3400   99.5600    1777
1   2022-10-07 19:55:00   99.4500   99.4500   99.4000   99.4000     633
2   2022-10-07 19:50:00   99.3500   99.4300   99.3500   99.4300     994
3   2022-10-07 19:45:00   99.4200   99.4200   99.4000   99.4000     932
4   2022-10-07 19:40:00   99.4200   99.4200   99.4200   99.4200     884
..                  ...       ...       ...       ...       ...     ...
95  2022-10-07 11:10:00  101.0900  101.0900  100.6100  100.6100  185531
96  2022-10-07 11:05:00  100.7600  101.0900  100.7600  101.0900  342552
97  2022-10-07 11:00:00  100.7800  100.9550  100.7250  100.7700  386668
98  2022-10-07 10:55:00  100.7300  100.8500  100.5500  100.7750  480951
99  2022-10-07 10:50:00  100.5500  100.8400  100.5000  100.7300  273143

[100 rows x 6 columns]

In [46]:
dt.today().strftime("%d/%m/%y")

'08/10/22'

In [48]:
df.to_json(f'./datalake/raw/file{dt.today().strftime("%d%m%y")}.json')

In [23]:
pd.read_json(f'./datalake/raw/file.json')

              datetime    open     high      low    close  volume
0  2022-10-07 20:00:00   99.35   99.560   99.340   99.560    1777
1  2022-10-07 19:55:00   99.45   99.450   99.400   99.400     633
2  2022-10-07 19:50:00   99.35   99.430   99.350   99.430     994
3  2022-10-07 19:45:00   99.42   99.420   99.400   99.400     932
4  2022-10-07 19:40:00   99.42   99.420   99.420   99.420     884
..                 ...     ...      ...      ...      ...     ...
95 2022-10-07 11:10:00  101.09  101.090  100.610  100.610  185531
96 2022-10-07 11:05:00  100.76  101.090  100.760  101.090  342552
97 2022-10-07 11:00:00  100.78  100.955  100.725  100.770  386668
98 2022-10-07 10:55:00  100.73  100.850  100.550  100.775  480951
99 2022-10-07 10:50:00  100.55  100.840  100.500  100.730  273143

[100 rows x 6 columns]

In [61]:
#url = 'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=GOOG&interval=5min&apikey=3B3IE0VNJFZBBMRY'
BASE_URL = 'https://www.alphavantage.co/query'
API_KEY = '3B3IE0VNJFZBBMRY'
STOCK_FN = 'TIME_SERIES_INTRADAY'
INTERVAL = '5min'

stock_symbol = {'google': 'GOOG', 'microsoft': 'MSFT', 'amazon': 'AMZN'}

In [90]:
for company in stock_symbol:
    print(company)

google
microsoft
amazon

In [28]:
end_point = (
        f"{BASE_URL}?function={STOCK_FN}&symbol={stock_symbol.get('google')}"
        f"&apikey={API_KEY}&datatype=json"
    )
end_point

'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=GOOG&apikey=TFHNYCWBD71JBSON&datatype=json'

In [30]:
requests.get(url).json()

{'Meta Data': {'1. Information': 'Intraday (5min) open, high, low, close prices and volume',
  '2. Symbol': 'GOOG',
  '3. Last Refreshed': '2022-10-07 20:00:00',
  '4. Interval': '5min',
  '5. Output Size': 'Compact',
  '6. Time Zone': 'US/Eastern'},
 'Time Series (5min)': {'2022-10-07 20:00:00': {'1. open': '99.3500',
   '2. high': '99.5600',
   '3. low': '99.3400',
   '4. close': '99.5600',
   '5. volume': '1777'},
  '2022-10-07 19:55:00': {'1. open': '99.4500',
   '2. high': '99.4500',
   '3. low': '99.4000',
   '4. close': '99.4000',
   '5. volume': '633'},
  '2022-10-07 19:50:00': {'1. open': '99.3500',
   '2. high': '99.4300',
   '3. low': '99.3500',
   '4. close': '99.4300',
   '5. volume': '994'},
  '2022-10-07 19:45:00': {'1. open': '99.4200',
   '2. high': '99.4200',
   '3. low': '99.4000',
   '4. close': '99.4000',
   '5. volume': '932'},
  '2022-10-07 19:40:00': {'1. open': '99.4200',
   '2. high': '99.4200',
   '3. low': '99.4200',
   '4. close': '99.4200',
   '5. volume': '884'},
  '2022-10-07 19:35:00': {'1. open': '99.5000',
   '2. high': '99.5000',
   '3. low': '99.4200',
   '4. close': '99.4200',
   '5. volume': '1196'},
  '2022-10-07 19:30:00': {'1. open': '99.5200',
   '2. high': '99.5200',
   '3. low': '99.5200',
   '4. close': '99.5200',
   '5. volume': '456'},
  '2022-10-07 19:25:00': {'1. open': '99.5200',
   '2. high': '99.5200',
   '3. low': '99.5200',
   '4. close': '99.5200',
   '5. volume': '130'},
  '2022-10-07 19:10:00': {'1. open': '99.5100',
   '2. high': '99.5100',
   '3. low': '99.5100',
   '4. close': '99.5100',
   '5. volume': '651'},
  '2022-10-07 19:00:00': {'1. open': '99.5600',
   '2. high': '99.5600',
   '3. low': '99.5600',
   '4. close': '99.5600',
   '5. volume': '210'},
  '2022-10-07 18:55:00': {'1. open': '99.5900',
   '2. high': '99.5900',
   '3. low': '99.5900',
   '4. close': '99.5900',
   '5. volume': '150'},
  '2022-10-07 18:50:00': {'1. open': '99.5900',
   '2. high': '99.5900',
   '3. low': '99.5900',
   '4. close': '99.5900',
   '5. volume': '132'},
  '2022-10-07 18:35:00': {'1. open': '99.5600',
   '2. high': '99.5600',
   '3. low': '99.5600',
   '4. close': '99.5600',
   '5. volume': '238'},
  '2022-10-07 18:30:00': {'1. open': '99.5300',
   '2. high': '99.5400',
   '3. low': '99.5300',
   '4. close': '99.5400',
   '5. volume': '1208'},
  '2022-10-07 18:25:00': {'1. open': '99.5500',
   '2. high': '99.5500',
   '3. low': '99.5500',
   '4. close': '99.5500',
   '5. volume': '4585'},
  '2022-10-07 18:20:00': {'1. open': '99.5600',
   '2. high': '99.5601',
   '3. low': '99.5500',
   '4. close': '99.5500',
   '5. volume': '999'},
  '2022-10-07 18:15:00': {'1. open': '99.5600',
   '2. high': '99.5600',
   '3. low': '99.5600',
   '4. close': '99.5600',
   '5. volume': '152'},
  '2022-10-07 18:10:00': {'1. open': '99.5600',
   '2. high': '99.5600',
   '3. low': '99.5600',
   '4. close': '99.5600',
   '5. volume': '258'},
  '2022-10-07 18:05:00': {'1. open': '99.6100',
   '2. high': '99.6100',
   '3. low': '99.5600',
   '4. close': '99.5600',
   '5. volume': '3132'},
  '2022-10-07 18:00:00': {'1. open': '99.6100',
   '2. high': '99.6100',
   '3. low': '99.6100',
   '4. close': '99.6100',
   '5. volume': '102'},
  '2022-10-07 17:55:00': {'1. open': '99.6300',
   '2. high': '99.6300',
   '3. low': '99.6300',
   '4. close': '99.6300',
   '5. volume': '106'},
  '2022-10-07 17:50:00': {'1. open': '99.6400',
   '2. high': '99.6400',
   '3. low': '99.6400',
   '4. close': '99.6400',
   '5. volume': '151'},
  '2022-10-07 17:45:00': {'1. open': '99.6300',
   '2. high': '99.6300',
   '3. low': '99.6300',
   '4. close': '99.6300',
   '5. volume': '400'},
  '2022-10-07 17:40:00': {'1. open': '99.6300',
   '2. high': '99.6300',
   '3. low': '99.6300',
   '4. close': '99.6300',
   '5. volume': '100'},
  '2022-10-07 17:35:00': {'1. open': '99.6200',
   '2. high': '99.6200',
   '3. low': '99.6200',
   '4. close': '99.6200',
   '5. volume': '105'},
  '2022-10-07 17:15:00': {'1. open': '99.6700',
   '2. high': '99.6700',
   '3. low': '99.5600',
   '4. close': '99.5600',
   '5. volume': '752'},
  '2022-10-07 17:00:00': {'1. open': '99.6000',
   '2. high': '99.6800',
   '3. low': '99.6000',
   '4. close': '99.6800',
   '5. volume': '2187'},
  '2022-10-07 16:55:00': {'1. open': '99.6500',
   '2. high': '99.6500',
   '3. low': '99.6200',
   '4. close': '99.6200',
   '5. volume': '1774'},
  '2022-10-07 16:50:00': {'1. open': '99.6400',
   '2. high': '99.6400',
   '3. low': '99.6400',
   '4. close': '99.6400',
   '5. volume': '535'},
  '2022-10-07 16:40:00': {'1. open': '99.6100',
   '2. high': '99.6399',
   '3. low': '99.5600',
   '4. close': '99.5600',
   '5. volume': '7344'},
  '2022-10-07 16:35:00': {'1. open': '99.5900',
   '2. high': '99.6000',
   '3. low': '99.5900',
   '4. close': '99.6000',
   '5. volume': '314'},
  '2022-10-07 16:30:00': {'1. open': '99.6200',
   '2. high': '99.6200',
   '3. low': '99.5500',
   '4. close': '99.5500',
   '5. volume': '10103'},
  '2022-10-07 16:25:00': {'1. open': '99.5900',
   '2. high': '99.6300',
   '3. low': '99.5800',
   '4. close': '99.6201',
   '5. volume': '999'},
  '2022-10-07 16:20:00': {'1. open': '99.6500',
   '2. high': '99.6500',
   '3. low': '99.6200',
   '4. close': '99.6200',
   '5. volume': '509'},
  '2022-10-07 16:15:00': {'1. open': '99.5700',
   '2. high': '99.7200',
   '3. low': '99.5600',
   '4. close': '99.7200',
   '5. volume': '23499'},
  '2022-10-07 16:10:00': {'1. open': '99.6900',
   '2. high': '99.7000',
   '3. low': '99.5700',
   '4. close': '99.6000',
   '5. volume': '48460'},
  '2022-10-07 16:05:00': {'1. open': '99.5700',
   '2. high': '99.8900',
   '3. low': '99.5700',
   '4. close': '99.6900',
   '5. volume': '839648'},
  '2022-10-07 16:00:00': {'1. open': '99.5300',
   '2. high': '99.7600',
   '3. low': '99.4200',
   '4. close': '99.6500',
   '5. volume': '1817533'},
  '2022-10-07 15:55:00': {'1. open': '99.4400',
   '2. high': '99.7800',
   '3. low': '99.3600',
   '4. close': '99.5300',
   '5. volume': '840233'},
  '2022-10-07 15:50:00': {'1. open': '99.5600',
   '2. high': '99.5700',
   '3. low': '99.3650',
   '4. close': '99.4300',
   '5. volume': '377385'},
  '2022-10-07 15:45:00': {'1. open': '99.5801',
   '2. high': '99.7200',
   '3. low': '99.4900',
   '4. close': '99.5600',
   '5. volume': '454946'},
  '2022-10-07 15:40:00': {'1. open': '99.2800',
   '2. high': '99.5900',
   '3. low': '99.2550',
   '4. close': '99.5900',
   '5. volume': '320402'},
  '2022-10-07 15:35:00': {'1. open': '99.4900',
   '2. high': '99.5000',
   '3. low': '99.2100',
   '4. close': '99.2700',
   '5. volume': '293568'},
  '2022-10-07 15:30:00': {'1. open': '99.6150',
   '2. high': '99.6300',
   '3. low': '99.3600',
   '4. close': '99.5000',
   '5. volume': '263224'},
  '2022-10-07 15:25:00': {'1. open': '99.6500',
   '2. high': '99.7031',
   '3. low': '99.5450',
   '4. close': '99.6100',
   '5. volume': '261555'},
  '2022-10-07 15:20:00': {'1. open': '99.7500',
   '2. high': '99.8200',
   '3. low': '99.6100',
   '4. close': '99.6600',
   '5. volume': '195727'},
  '2022-10-07 15:15:00': {'1. open': '99.8900',
   '2. high': '99.9700',
   '3. low': '99.7200',
   '4. close': '99.7499',
   '5. volume': '223635'},
  '2022-10-07 15:10:00': {'1. open': '100.0900',
   '2. high': '100.0950',
   '3. low': '99.8050',
   '4. close': '99.8850',
   '5. volume': '175739'},
  '2022-10-07 15:05:00': {'1. open': '99.8300',
   '2. high': '100.1000',
   '3. low': '99.8300',
   '4. close': '100.1000',
   '5. volume': '171781'},
  '2022-10-07 15:00:00': {'1. open': '99.7800',
   '2. high': '99.8600',
   '3. low': '99.7200',
   '4. close': '99.8300',
   '5. volume': '168309'},
  '2022-10-07 14:55:00': {'1. open': '99.7050',
   '2. high': '99.7850',
   '3. low': '99.6600',
   '4. close': '99.7799',
   '5. volume': '179802'},
  '2022-10-07 14:50:00': {'1. open': '99.5700',
   '2. high': '99.7000',
   '3. low': '99.5400',
   '4. close': '99.6950',
   '5. volume': '183714'},
  '2022-10-07 14:45:00': {'1. open': '99.5300',
   '2. high': '99.6690',
   '3. low': '99.5300',
   '4. close': '99.5700',
   '5. volume': '131054'},
  '2022-10-07 14:40:00': {'1. open': '99.4200',
   '2. high': '99.6400',
   '3. low': '99.4200',
   '4. close': '99.5378',
   '5. volume': '158976'},
  '2022-10-07 14:35:00': {'1. open': '99.3900',
   '2. high': '99.4350',
   '3. low': '99.2700',
   '4. close': '99.4200',
   '5. volume': '193769'},
  '2022-10-07 14:30:00': {'1. open': '99.4000',
   '2. high': '99.4900',
   '3. low': '99.3500',
   '4. close': '99.3900',
   '5. volume': '173167'},
  '2022-10-07 14:25:00': {'1. open': '99.5300',
   '2. high': '99.5700',
   '3. low': '99.3500',
   '4. close': '99.3900',
   '5. volume': '181553'},
  '2022-10-07 14:20:00': {'1. open': '99.6800',
   '2. high': '99.7300',
   '3. low': '99.5100',
   '4. close': '99.5350',
   '5. volume': '133298'},
  '2022-10-07 14:15:00': {'1. open': '99.5700',
   '2. high': '99.7001',
   '3. low': '99.4200',
   '4. close': '99.6800',
   '5. volume': '170238'},
  '2022-10-07 14:10:00': {'1. open': '99.5100',
   '2. high': '99.6200',
   '3. low': '99.5000',
   '4. close': '99.5800',
   '5. volume': '122766'},
  '2022-10-07 14:05:00': {'1. open': '99.4900',
   '2. high': '99.5800',
   '3. low': '99.4300',
   '4. close': '99.5150',
   '5. volume': '182280'},
  '2022-10-07 14:00:00': {'1. open': '99.5700',
   '2. high': '99.6600',
   '3. low': '99.4300',
   '4. close': '99.4900',
   '5. volume': '158925'},
  '2022-10-07 13:55:00': {'1. open': '99.6600',
   '2. high': '99.7194',
   '3. low': '99.5650',
   '4. close': '99.5799',
   '5. volume': '129149'},
  '2022-10-07 13:50:00': {'1. open': '99.7700',
   '2. high': '99.8900',
   '3. low': '99.6550',
   '4. close': '99.6650',
   '5. volume': '174263'},
  '2022-10-07 13:45:00': {'1. open': '99.7100',
   '2. high': '99.8900',
   '3. low': '99.7000',
   '4. close': '99.7800',
   '5. volume': '148333'},
  '2022-10-07 13:40:00': {'1. open': '99.7200',
   '2. high': '99.7800',
   '3. low': '99.6550',
   '4. close': '99.7150',
   '5. volume': '122376'},
  '2022-10-07 13:35:00': {'1. open': '99.8500',
   '2. high': '99.8500',
   '3. low': '99.6750',
   '4. close': '99.7283',
   '5. volume': '148724'},
  '2022-10-07 13:30:00': {'1. open': '99.7800',
   '2. high': '99.9650',
   '3. low': '99.7700',
   '4. close': '99.8500',
   '5. volume': '128095'},
  '2022-10-07 13:25:00': {'1. open': '99.9700',
   '2. high': '99.9850',
   '3. low': '99.7800',
   '4. close': '99.7800',
   '5. volume': '121085'},
  '2022-10-07 13:20:00': {'1. open': '99.9100',
   '2. high': '100.0300',
   '3. low': '99.8600',
   '4. close': '99.9800',
   '5. volume': '140688'},
  '2022-10-07 13:15:00': {'1. open': '99.6800',
   '2. high': '99.9100',
   '3. low': '99.6800',
   '4. close': '99.9098',
   '5. volume': '149416'},
  '2022-10-07 13:10:00': {'1. open': '99.7700',
   '2. high': '99.8358',
   '3. low': '99.6200',
   '4. close': '99.6737',
   '5. volume': '128559'},
  '2022-10-07 13:05:00': {'1. open': '99.8900',
   '2. high': '99.8900',
   '3. low': '99.6900',
   '4. close': '99.7615',
   '5. volume': '157706'},
  '2022-10-07 13:00:00': {'1. open': '99.8094',
   '2. high': '99.9100',
   '3. low': '99.7975',
   '4. close': '99.9000',
   '5. volume': '129056'},
  '2022-10-07 12:55:00': {'1. open': '99.7800',
   '2. high': '99.8550',
   '3. low': '99.7400',
   '4. close': '99.8000',
   '5. volume': '122139'},
  '2022-10-07 12:50:00': {'1. open': '99.9600',
   '2. high': '99.9800',
   '3. low': '99.7498',
   '4. close': '99.7700',
   '5. volume': '148642'},
  '2022-10-07 12:45:00': {'1. open': '100.0500',
   '2. high': '100.0700',
   '3. low': '99.9100',
   '4. close': '99.9500',
   '5. volume': '127086'},
  '2022-10-07 12:40:00': {'1. open': '99.9100',
   '2. high': '100.0500',
   '3. low': '99.9000',
   '4. close': '100.0488',
   '5. volume': '122494'},
  '2022-10-07 12:35:00': {'1. open': '99.9300',
   '2. high': '99.9900',
   '3. low': '99.8500',
   '4. close': '99.9100',
   '5. volume': '172077'},
  '2022-10-07 12:30:00': {'1. open': '99.9100',
   '2. high': '100.0600',
   '3. low': '99.8500',
   '4. close': '99.9400',
   '5. volume': '168160'},
  '2022-10-07 12:25:00': {'1. open': '100.2200',
   '2. high': '100.2600',
   '3. low': '99.9100',
   '4. close': '99.9100',
   '5. volume': '248627'},
  '2022-10-07 12:20:00': {'1. open': '100.2100',
   '2. high': '100.3200',
   '3. low': '100.1400',
   '4. close': '100.2150',
   '5. volume': '136867'},
  '2022-10-07 12:15:00': {'1. open': '100.3100',
   '2. high': '100.3650',
   '3. low': '100.1950',
   '4. close': '100.2000',
   '5. volume': '125596'},
  '2022-10-07 12:10:00': {'1. open': '100.3200',
   '2. high': '100.3600',
   '3. low': '100.1800',
   '4. close': '100.3100',
   '5. volume': '118518'},
  '2022-10-07 12:05:00': {'1. open': '100.2500',
   '2. high': '100.3100',
   '3. low': '100.1700',
   '4. close': '100.3100',
   '5. volume': '139159'},
  '2022-10-07 12:00:00': {'1. open': '100.1500',
   '2. high': '100.3500',
   '3. low': '100.1250',
   '4. close': '100.2500',
   '5. volume': '123106'},
  '2022-10-07 11:55:00': {'1. open': '100.1100',
   '2. high': '100.2800',
   '3. low': '100.0600',
   '4. close': '100.1525',
   '5. volume': '125005'},
  '2022-10-07 11:50:00': {'1. open': '100.2100',
   '2. high': '100.2550',
   '3. low': '100.0900',
   '4. close': '100.1010',
   '5. volume': '155306'},
  '2022-10-07 11:45:00': {'1. open': '100.3200',
   '2. high': '100.3800',
   '3. low': '100.0650',
   '4. close': '100.2000',
   '5. volume': '174051'},
  '2022-10-07 11:40:00': {'1. open': '100.2250',
   '2. high': '100.4500',
   '3. low': '100.2250',
   '4. close': '100.3290',
   '5. volume': '143688'},
  '2022-10-07 11:35:00': {'1. open': '100.3900',
   '2. high': '100.4900',
   '3. low': '100.1950',
   '4. close': '100.2200',
   '5. volume': '145373'},
  '2022-10-07 11:30:00': {'1. open': '100.2384',
   '2. high': '100.4100',
   '3. low': '100.1600',
   '4. close': '100.3900',
   '5. volume': '176082'},
  '2022-10-07 11:25:00': {'1. open': '100.3200',
   '2. high': '100.3600',
   '3. low': '100.1600',
   '4. close': '100.2300',
   '5. volume': '220553'},
  '2022-10-07 11:20:00': {'1. open': '100.6350',
   '2. high': '100.7300',
   '3. low': '100.3100',
   '4. close': '100.3200',
   '5. volume': '192981'},
  '2022-10-07 11:15:00': {'1. open': '100.6100',
   '2. high': '100.7390',
   '3. low': '100.4900',
   '4. close': '100.6300',
   '5. volume': '171871'},
  '2022-10-07 11:10:00': {'1. open': '101.0900',
   '2. high': '101.0900',
   '3. low': '100.6100',
   '4. close': '100.6100',
   '5. volume': '185531'},
  '2022-10-07 11:05:00': {'1. open': '100.7600',
   '2. high': '101.0900',
   '3. low': '100.7600',
   '4. close': '101.0900',
   '5. volume': '342552'},
  '2022-10-07 11:00:00': {'1. open': '100.7800',
   '2. high': '100.9550',
   '3. low': '100.7250',
   '4. close': '100.7700',
   '5. volume': '386668'},
  '2022-10-07 10:55:00': {'1. open': '100.7300',
   '2. high': '100.8500',
   '3. low': '100.5500',
   '4. close': '100.7750',
   '5. volume': '480951'},
  '2022-10-07 10:50:00': {'1. open': '100.5500',
   '2. high': '100.8400',
   '3. low': '100.5000',
   '4. close': '100.7300',
   '5. volume': '273143'}}}

In [85]:

def ingest_data (company):
    end_point = (f"{BASE_URL}?function={STOCK_FN}&symbol=GOOD&interval={INTERVAL}"f"&apikey={API_KEY}&datatype=json")
    data = requests.get(end_point).json()
    df = pd.DataFrame(data.get('Time Series (5min)')).T.reset_index().rename(columns={'index':'datetime', 
                                                                             '1. open': 'open', 
                                                                             '2. high': 'high', 
                                                                             '3. low':'low', 
                                                                             '4. close': 'close', 
                                                                             '5. volume': 'volume'})
    df['symbol'] = company
    df.to_json(f'./datalake/rawfile-{company}-{df.loc[0,["datetime"]].datetime[0:10]}.json')
    return df

In [86]:
ingest_data('google')

               datetime     open     high      low    close volume  symbol
0   2022-10-07 18:25:00  15.9100  15.9100  15.9100  15.9100    450  google
1   2022-10-07 17:50:00  15.4000  15.4000  15.4000  15.4000   1000  google
2   2022-10-07 16:05:00  15.4300  15.4300  15.4300  15.4300   4828  google
3   2022-10-07 16:00:00  15.4450  15.4600  15.4300  15.4300  13723  google
4   2022-10-07 15:55:00  15.4000  15.4600  15.4000  15.4400  17742  google
..                  ...      ...      ...      ...      ...    ...     ...
95  2022-10-06 15:05:00  15.5870  15.5900  15.5800  15.5800   3795  google
96  2022-10-06 15:00:00  15.5800  15.6000  15.5800  15.5900   1271  google
97  2022-10-06 14:55:00  15.5900  15.5900  15.5600  15.5600    682  google
98  2022-10-06 14:50:00  15.6100  15.6200  15.6100  15.6100   1443  google
99  2022-10-06 14:40:00  15.6200  15.6300  15.6200  15.6300    910  google

[100 rows x 7 columns]

In [91]:
import numpy as np

In [123]:
APIKEYS = ['7C5G34M2E03NDYL3', 'P7TV6UJVGDYPDTUR', 'TFHNYCWBD71JBSON']
np.random.choice(APIKEYS, 1)[0]

'TFHNYCWBD71JBSON'